- etl_framework/Exceptions.py
> add schema related exceptions

- etl_framework/BaseEtlSetUp.py
- etl_framework/config_mixins/JobMixin.py
Add attributes to JobConfig to set `etl_job_id` and `etl_job_name`
> Add job_id and job_name attributes

- etl_framework/config_mixins/AddFiltersMixin.py
- etl_framework/config_mixins/FiltersMixin.py
This adds a function to use when adding filters from a module as opposed to a adding them from a dictionary
#29 
@michaelliu2
> add add_filters_from_module

- etl_framework/config_mixins/FieldMappingsMixin.py
@michaelliu2 does this seem right?
> add_filters_from_module in FieldMappingsMixin as well

- etl_framework/Loader.py
- etl_framework/MySqlSchemaModifier.py
- etl_framework/datastores/__init__.py
- etl_framework/loaders/PostgreSqlLoader.py
@ianlofs @hdahme Restructuring so that pubsub-etl passes tests
> Restructure imports

- etl_framework/MySqlDatabase.py
> Clarifying an exception

- .pylint
- etl_framework/config_mixins/InsertStatementMixin.py
- etl_framework/config_mixins/UpsertStatementMixin.py
This commit adds support for a postgresql upsert
loader as well as does some light refactoring
of the current upsert code.
see [MAGE-659](https://getpantheon.atlassian.net/browse/MAGE-659)
@hdahme @michaelliu2
> feature(loader): loader for postgresql upsert

- etl_framework/config_mixins/UpsertStatementMixin.py
This provides a fix for the create_upsert_statement in the mysql upsert config mixin. 
@michaelliu2
> hotfix for mysql upsert config

- etl_framework/datastore_interfaces/sql_database_interface.py
pinging is a mysql specific behavior
@michaelliu2
> create a new connection when a connection gets drop instead of pinging

- etl_framework/MySqlSchemaModifier.py
- etl_framework/SqlSchemaConfig.py
- etl_framework/config_mixins/TruncateTableStatementMixin.py
@hdahme @ianlofs Truncate table for feature flag stuff.  This is Harrison's work a minor change
> Truncate table statement

- etl_framework/BufferedLoader.py
- etl_framework/Loader.py
- etl_framework/loaders/MySqlBufferedLoader.py
- etl_framework/loaders/MySqlLoader.py
> add a mysql buffered loader

- etl_framework/config_mixins/DsnMixin.py
> set dsn from dsn type in config

- etl_framework/BaseEtlSetUp.py
- etl_framework/datastore_interfaces/sql_database_interface.py
> EtlSetup creates database if not exists

- etl_framework/config_mixins/CredentialsMixin.py
> use configs to select for credential type

- etl_framework/BaseEtlSetUp.py
> hot fix for parsing dsn

- etl_framework/BufferedLoader.py
> Fix import path raised in expcetion

- etl_framework/BaseEtlSetUp.py
> add record_updated and estimated_completion_at fields to etl_jobs table

- etl_framework/config_mixins/UpsertStatementMixin.py
> proper coalesce statement

- environment.yml
- etl_framework/config_mixins/UpdateStatementMixin.py
> add support for explicit where where values in where clause

- etl_framework/etl_class.py
@ianlofs @hdahme 
EtlClass is a new-style class that can be inherited from using super.
> EtlClass uses super

- etl_framework/config_mixins/FieldMappingsMixin.py
> Raise more specific Exception

- etl_framework/config_mixins/DestinationMixin.py
@ianlofs @hdahme
iter_destination_chooser outputs multiple destinations for a row
> Ability to specify multiple destinations

- .pylint
- circle.yml
- etl_framework/BaseEtlSetUp.py
- etl_framework/config_mixins/TruncateTableStatementMixin.py
- etl_framework/config_mixins/UpdateStatementMixin.py
- etl_framework/config_mixins/UpsertStatementMixin.py
- gcloud/configs/bigquery_loader.py
- gcloud/configs/pubsub_extractor.py
- gcloud/datastores/pubsub.py
- requirements.txt
Cassandra etl is failing because some job_ids are null. This fixes that issues
> Insert ignore etl job row
